import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer.js";
import Navbar from "./components/Navbar.js";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" mt-16">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
